// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-quotes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_quotes_default = defineTool({
  name: "list_my_quotes",
  title: "List mine tilbud",
  description: "Hent innlogget brukers tilbudsforesp\xF8rsler fra HandyHjelp.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maks antall (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("quotes").select("id, type, name, email, phone, description, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-agreements.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_agreements_default = defineTool2({
  name: "list_my_agreements",
  title: "List mine serviceavtaler",
  description: "Hent innlogget brukers serviceavtaler.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("service_agreements").select("id, contact_person, email, address, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { agreements: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-jobs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_jobs_default = defineTool3({
  name: "list_my_jobs",
  title: "List mine jobber",
  description: "Hent innlogget brukers jobber/oppdrag hos HandyHjelp.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("jobs").select("id, title, description, status, scheduled_date, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pending-quotes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function hasStaffRole(ctx) {
  const supabase = supabaseForUser4(ctx);
  const { data } = await supabase.from("user_roles").select("role").eq("user_id", ctx.getUserId());
  const roles = (data ?? []).map((r) => r.role);
  return roles.some((r) => ["admin", "worker", "platform_owner"].includes(r));
}
var list_pending_quotes_default = defineTool4({
  name: "list_pending_quotes",
  title: "List ubehandlede tilbud",
  description: "Hent alle tilbud med status 'pending'. Kun tilgjengelig for admin/worker/eier.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    if (!await hasStaffRole(ctx)) {
      return { content: [{ type: "text", text: "Krever admin/worker-rolle" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("quotes").select("id, type, name, email, phone, description, created_at").eq("status", "pending").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-analytics-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function isAdminOrOwner(ctx) {
  const supabase = supabaseForUser5(ctx);
  const { data } = await supabase.from("user_roles").select("role").eq("user_id", ctx.getUserId());
  const roles = (data ?? []).map((r) => r.role);
  return roles.some((r) => ["admin", "platform_owner"].includes(r));
}
var get_analytics_summary_default = defineTool5({
  name: "get_analytics_summary",
  title: "Analyseoppsummering",
  description: "Hent HandyHjelp analytics-oppsummering (siste N dager). Kun admin/eier.",
  inputSchema: {
    days: z5.number().int().min(1).max(90).optional().describe("Antall dager tilbake (default 7)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    if (!await isAdminOrOwner(ctx)) {
      return { content: [{ type: "text", text: "Krever admin-/eier-rolle" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const from = new Date(Date.now() - (days ?? 7) * 864e5).toISOString();
    const { data, error } = await supabase.functions.invoke("analytics-summary", {
      body: { from }
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { summary: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bwwodqzhkehirerzlzpu";
var mcp_default = defineMcp({
  name: "handyhjelp-mcp",
  title: "HandyHjelp",
  version: "0.1.0",
  instructions: "Verkt\xF8y for HandyHjelp. Innlogget bruker kan hente sine egne tilbud, serviceavtaler og jobber. Admin/eier kan i tillegg hente analytics-oppsummering og ubehandlede tilbud.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_quotes_default,
    list_my_agreements_default,
    list_my_jobs_default,
    list_pending_quotes_default,
    get_analytics_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
